# --- Server ---
server.port=${SERVER_PORT:8080}
server.address=0.0.0.0
# --- Datasource (Override via environment variables) ---
spring.datasource.url=jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:user-account}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
